BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "mosquito_data" (
	"SEASON YEAR"	INTEGER,
	"WEEK"	INTEGER,
	"BLOCK"	TEXT,
	"TRAP"	TEXT,
	"TRAP_TYPE"	TEXT,
	"TEST DATE"	TEXT,
	"NUMBER OF MOSQUITOS"	INTEGER,
	"RESULT"	TEXT,
	"SPECIES"	TEXT,
	"LATITUDE"	REAL,
	"LONGITUDE"	REAL,
	"LOCATION"	TEXT,
	"Wards"	INTEGER,
	"Census Tracts"	INTEGER,
	"Zip Codes"	INTEGER,
	"Community Areas"	INTEGER,
	"Historical Wards 2003-2015"	INTEGER
);
COMMIT;
